{% set conda_name = "pyemma" %}
{% set name = "pyEMMA" %} 
{% set version = "2.5.1" %}
{% set sha256 = "1ec0b78f76d6eae2273e582748afdd762d8628ddc39ff64195984190c266b281" %}

package:
  name: {{ conda_name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -B setup.py install --single-version-externally-managed --record record.txt
  # skip this, because we would need to built extension with vc14, but ci is configured to use vc9 for py27
  skip: True  # [win and py27]

requirements:
  build:
    - cython
    - mdtraj >=1.8
    - python
    - setuptools
    # actually we could build with np18, but fastcluster (dep of mdtraj, we link against) is only avail for 1.9
    - numpy 1.9.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - toolchain
    - scipy
  run:
    - bhmm >=0.6,<0.7
    - decorator >=4.0.0
    - h5py
    - matplotlib
    - mdtraj >=1.8
    - mock
    - msmtools >=1.2
    - numpy >=1.9,<1.14  # [not (win and (py35 or py36))]
    - numpy >=1.9,<1.14  # [win and py35]
    - numpy >=1.11,<1.14  # [win and py36]
    - pathos
    - psutil >=3.1.1
    - python
    - pyyaml
    - scipy
    - setuptools
    - six >=1.1.0
    - thermotools >=0.2.6
    - tqdm

test:
  imports:
    - pyemma

about:
  home: http://github.com/markovmodel/pyemma
  license: LGPLv3+ 
  license_file: LICENSE.txt
  summary: "PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package for analysis of extensive molecular dynamics simulations"

  description: |
    PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package
    for analysis of extensive molecular dynamics simulations.
    In particular, it includes algorithms for estimation, validation and analysis of:
      * Clustering and Featurization
      * Markov state models (MSMs)
      * Hidden Markov models (HMMs)
      * Multi-ensemble Markov models (MEMMs)
      * Time-lagged independent component analysis (TICA)
      * Transition Path Theory (TPT)
  doc_url: http://emma-project.org
  dev_url: https://github.com/markovmodel/pyemma

extra:
  recipe-maintainers:
    - franknoe
    - marscher
