travis:
  secure:
    BINSTAR_TOKEN: sb7fV18NlUo0aBlQGA6fRmn4uIXg1fTsjIKeGxVk6gevSXu7RoQ6crCkVWnc+w2MnCiXo5f6inOal40nVFoF9QiBylLRyxfPDY8/j2YjfWr3FeLuDXvKWUFpcJMphPQJCh5R0k0uherY6XRmLO1qzB79GM6jvHU5QXQX0wQmqiMhr1IxcnRt3QsnsU+RzyYV24HZzuwmBwmaSwt2HtjaJ6ESkyXQg2luNJiH0y9VeuuH7t6qGhrzjwXcWlTYJe0ELBKU72PSj0s8gqgM5CW0A4mRC7oJ7VzWaP+Vrv1RAnhnIJHqH2eVwY84+WC099pgll7AeHm/3RHoCY+wf+qGxbS4y311dgyFrrlcgcLGqDTCVJNvt3uxT0LrcpFh+oFJeIiKsyNSqihrg4lRjGHAB+rfb7ZaYwnBNFj95MT1/v54a/5PTWWG4WrqCLVvBND4Yr1Hq8k2H7BmUlMHl1Ua8vibu3r/26Hu8XtIvrShB6VrD3N6XrPlV3hCPPdXrxuznfS5nsgAzN9kDLHICjRNE0q3jhwsTgn+LATkkFJNZYJvEdNfANVPlWpiDcj5HsTrtCgv7IQsbwNHn0fT5Jv/OqJY2pXnQ093acwIiFLBWtNol8joq1HlbtkLkhzhURSz7VtVbSRhBKGLpI/u1vzdtHA14rDXlJJKhbP2ssedWO4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
