travis:
  secure:
    BINSTAR_TOKEN: fAxr76AB4YG0zC0NOpMEia6S9moK+bDEAVZ5HiGZrfqDJ03AZPUPh7Rsjsl22055Md1hvwBwp9dNh682cIaNdl7O9K9yWsZnGHvFou/IiLTTIG5M8IqnJfxh0ozfhK0AoZBNWEF0BNuVLDZbQJbo9SL8rrzTWkhv77SfcemXzCMroJCDAT09AozvteBCEvCtE94qBEZ++YrKxgmcmV8X9woLHi1LTQ5enUfKpd2ftJYUv1sBCDZ463DwFLMVJnoccgXc/6ma+77n02l/TzlQ2UTbYN2CXWXbZ2z0YLqwUX7H8t06KtSVnFk4WyQS9Ia/rcXXTyyxT7r5UAoObgud8OHw6nogOp7GwFgWblLIDdpM80JcPIcFzpnb/n/LYMjpfywld91MOCs8agvIJ5bav+iHkbN3mx2+MmZccIEwwr8LmsbSYJ/fc4JK2WjKQgD84LJ+xPEV0yCgQrvhOaCWm3LW4TFm85u6easoWnR2oMekeI29F78+8I8zXAFowxRVUEe8ha0pmPg0fHoppF3Ugj/LuDzuCij+I3uWDVIlDMTjwj4Utytz3VzOFFnnuuI/WuoxPD/yxrRh76ugUfKv6bYPklflnPd3/WMermeYbVg9qCNgVuD58ELrc6kC88C5WCsHc8ABDClVvlNGItNnpW3yp2+GeYGAiK7MvSNRttY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
